---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present
- name: Download file from URL
  get_url:
    url: "{{ kibana_url }}"
    dest: "{{ home_directory }}/{{ kibana_dpkg }}"
- name: install deb-package
  apt:
    deb: "{{ home_directory }}/{{ kibana_dpkg }}"
    state: present
