---
- name: Install and configure nginx for static website hosting
  hosts: nginx
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes

