---
- name: Install zabbix-server
  hosts: zabbix-server
  become: true
  become_user: stanislav
  roles:
    - role: community.zabbix.zabbix_server
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      

