---
- name: Install zabbix-web   
  hosts: zabbix-server
  become: true
  become_user: root
  roles:
    - role: community.zabbix.zabbix_web
      zabbix_api_server_url: zabbix.example.com
      zabbix_server_database: mysql
      zabbix_db_type_long: mysql
      zabbix_server_dbport: 3306
